DATA_PATH = '/Users/gil-arnaudcoche/Documents/ijoutaku/data/'
UCSD_PATH = f'{DATA_PATH}UCSD_Anomaly_Dataset.v1p2/UCSDped1/'
TRAIN_PATH = f'{UCSD_PATH}Train/'
TEST_PATH = f'{UCSD_PATH}Test/'
MODELS_PATH = f'{DATA_PATH}models/'